In [2]:
import numpy as np

In [3]:
arr = np.random.randint(0,50,25).reshape(5,5)

In [4]:
arr

array([[18, 33, 16, 19,  8],
       [ 4, 16, 48, 33, 34],
       [ 0, 47, 40, 40, 41],
       [10, 30, 46, 12, 15],
       [25, 15, 32, 49, 20]])

In [5]:
print(arr.shape)

(5, 5)


In [6]:
print(arr.ndim)

2


In [7]:
#3d Array
arr = np.random.randint(0,50,20).reshape(2,5,2)

In [8]:
arr

array([[[ 6, 32],
        [13, 19],
        [48,  9],
        [36, 37],
        [ 9, 23]],

       [[38,  8],
        [11,  6],
        [16, 34],
        [17, 41],
        [26, 21]]])

In [9]:
arr.shape

(2, 5, 2)

In [10]:
arr.ndim

3

In [11]:
a = np.random.randint(0,20,9).reshape(3,3)

In [12]:
a

array([[ 5, 15, 12],
       [17,  2, 14],
       [ 7, 15,  1]])

In [13]:
b = np.random.randint(0,20,9).reshape(3,3)

In [14]:
b

array([[15,  2,  5],
       [ 6,  1,  5],
       [ 1,  4,  5]])

In [15]:
if (a.all()==b.all()):
    print('True')
else:
    print('False')

True


In [29]:
np.array_equal(a,b)

False

In [30]:
a+b

array([[20, 17, 17],
       [23,  3, 19],
       [ 8, 19,  6]])

In [31]:
a*b

array([[ 75,  30,  60],
       [102,   2,  70],
       [  7,  60,   5]])

In [32]:
a.dot(b)

array([[177,  73, 160],
       [281,  92, 165],
       [196,  33, 115]])

In [36]:
np.add(a,b)

array([[20, 17, 17],
       [23,  3, 19],
       [ 8, 19,  6]])

In [40]:
A = [[2, 5], [5,8]]
np.dot(A,7)

array([[14, 35],
       [35, 56]])

In [50]:
A = np.random.randint(0,20,9).reshape(3,3)
B = np.random.randint(20,50,9).reshape(3,3)

In [51]:
A

array([[ 8, 14,  2],
       [12,  5,  3],
       [15, 17,  0]])

In [52]:
B

array([[30, 20, 40],
       [29, 32, 26],
       [36, 40, 43]])

In [59]:
%%timeit
print(A*B)

[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [54

 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [3

[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [54

 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [3

[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [54

 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [3

 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [3

 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [3

 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [3

 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [3

 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [348 160  78]
 [540 680   0]]
[[240 280  80]
 [3

In [61]:
%%timeit
print(A.dot(B))

[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  68

 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  84

 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  84

 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  84

 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  84

 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  84

 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  84

 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  84

 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  84

 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  84

 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  84

In [60]:
%%timeit
print(A@B)

[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  68

[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  68

[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  68

 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  84

 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  84

 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  84

[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  68

 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  84

[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  68

 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  84

 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  84

 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  844 1042]]
[[ 718  688  770]
 [ 613  520  739]
 [ 943  84

In [56]:
np.matmul(A,B)

array([[ 718,  688,  770],
       [ 613,  520,  739],
       [ 943,  844, 1042]])