In [1]:
import numpy as np

In [4]:
# Transpose the Matrix
A = np.random.randint(0,10,9).reshape(3,3)
A

array([[0, 5, 0],
       [6, 7, 6],
       [7, 5, 5]])

In [6]:
np.transpose(A)

array([[0, 6, 7],
       [5, 7, 5],
       [0, 6, 5]])

In [7]:
A.T

array([[0, 6, 7],
       [5, 7, 5],
       [0, 6, 5]])